// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.
#include <stdint.h>
#include <arpa/inet.h>
#include "MtExampleService.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TThreadPoolServer.h>
#include <thrift/server/TNonblockingServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>
#include <thrift/concurrency/PlatformThreadFactory.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using namespace ::apache::thrift::concurrency;

using boost::shared_ptr;


class MtExampleServiceHandler : virtual public MtExampleServiceIf {
 public:
  MtExampleServiceHandler() {
    // Your initialization goes here
  }

  int32_t SetUserProfile(const UserProfile& oProfile) {
    // Your implementation goes here
    printf("SetUserProfile\n");
  }

  void GetUserProfile(UserProfile& _return, const int32_t userId) {
    // Your implementation goes here
    printf("GetUserProfile\n");
  }

};

int main(int argc, char **argv) {
	int port = 9090;
	shared_ptr<MtExampleServiceHandler> handler(new MtExampleServiceHandler());
	shared_ptr<TProcessor> processor(new MtExampleServiceProcessor(handler));


	shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));    
	shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());    
	shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());    
	shared_ptr<ThreadManager> threadManager =        
		ThreadManager::newSimpleThreadManager(1);    
	shared_ptr<PosixThreadFactory> threadFactory =   
		shared_ptr<PosixThreadFactory>(new PosixThreadFactory());    
	threadManager->threadFactory(threadFactory);    
	threadManager->start();    
	TNonblockingServer server(processor, 
								protocolFactory,            
								port,            
								threadManager);    
	printf("Starting the server...\n");    
	server.serve();    
	printf("done.\n");    

	return 0;
}

