/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef example_CONSTANTS_H
#define example_CONSTANTS_H

#include "example_types.h"



class exampleConstants {
 public:
  exampleConstants();

};

extern const exampleConstants g_example_constants;



#endif
